In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!nvidia-smi

Thu Dec  8 12:28:47 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 32.4 MB/s 
     |████████████████████████████████| 182 kB 72.6 MB/s 
     |████████████████████████████████| 7.6 MB 55.5 MB/s 


In [4]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import tensorflow as tf
from transformers import BertTokenizer

In [6]:
df = pd.read_csv('/content/drive/MyDrive/TrainingData.csv')

In [7]:
df

CID                                               Text  class
0          0  3fa9e6ac4a36c66b8ca3887914c6c75b08dad9095f1d7a...      3
1          1  21b7f56f644f02d51ae82c9d50f69fad686319657712d4...      2
2          2  74203af11b8bbb1d31ac34e85f3076588fbbf2dcf1a4f7...      3
3          3  6b412e99f1dea02c124a90b5f2cf29496cb84f2b2b33a0...      1
4          4  5b84fb6fc7710b0e499394d9b406950d2436a118e2d867...      1
...      ...                                                ...    ...
79995  79995  888216a483866a9020360c92348576ea8b2dea8291422b...      2
79996  79996  7087c314dd336654d5a0dd4bff761a8a631bc3b58119f6...      3
79997  79997  391b30539b56b3236ce468b46e39eaf51945f7306b3fd4...      0
79998  79998  c8a58f604a35afad7a47d2b87f111c643374dfe15c7ef3...      0
79999  79999  4c25a945815e9767b62ebd463139234e7a58266b369f2a...      0

[80000 rows x 3 columns]

In [8]:
df['class'].value_counts()

0    20048
1    20020
2    19970
3    19962
Name: class, dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   CID     80000 non-null  int64 
 1   Text    80000 non-null  object
 2   class   80000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.8+ MB


In [10]:
df.set_index('CID', inplace=True)
df

Text  class
CID                                                            
0      3fa9e6ac4a36c66b8ca3887914c6c75b08dad9095f1d7a...      3
1      21b7f56f644f02d51ae82c9d50f69fad686319657712d4...      2
2      74203af11b8bbb1d31ac34e85f3076588fbbf2dcf1a4f7...      3
3      6b412e99f1dea02c124a90b5f2cf29496cb84f2b2b33a0...      1
4      5b84fb6fc7710b0e499394d9b406950d2436a118e2d867...      1
...                                                  ...    ...
79995  888216a483866a9020360c92348576ea8b2dea8291422b...      2
79996  7087c314dd336654d5a0dd4bff761a8a631bc3b58119f6...      3
79997  391b30539b56b3236ce468b46e39eaf51945f7306b3fd4...      0
79998  c8a58f604a35afad7a47d2b87f111c643374dfe15c7ef3...      0
79999  4c25a945815e9767b62ebd463139234e7a58266b369f2a...      0

[80000 rows x 2 columns]

In [11]:
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [12]:
token = tokenizer.encode_plus(
    df['Text'][0],
    max_length = 256,
    truncation = True,
    padding = 'max_length',
    add_special_tokens = True,
    return_tensors = 'tf'
)

In [13]:
token

{'input_ids': <tf.Tensor: shape=(1, 256), dtype=int32, numpy=
array([[101, 100, 102,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,

In [14]:
X_input_ids = np.zeros((len(df), 256))
X_attn_masks = np.zeros((len(df), 256))

In [15]:
X_input_ids.shape

(80000, 256)

In [16]:
def generate_training_data(df, ids, masks, tokenizer):
    for i, text in tqdm(enumerate(df['Text'])):
        tokenized_text = tokenizer.encode_plus(
            text,
            max_length=256, 
            truncation=True, 
            padding='max_length', 
            add_special_tokens=True,
            return_tensors='tf'
        )
        ids[i, :] = tokenized_text.input_ids
        masks[i, :] = tokenized_text.attention_mask
    return ids, masks

In [17]:
X_input_ids, X_attn_masks = generate_training_data(df, X_input_ids, X_attn_masks, tokenizer)

0it [00:00, ?it/s]

In [18]:
labels = np.zeros((len(df), 4))
labels.shape

(80000, 4)

In [19]:
labels[np.arange(len(df)), df['class'].values] = 1

In [20]:
labels

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [21]:
# creating a data pipeline using tensorflow dataset utility, creates batches of data for easy loading...
dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, labels))
dataset.take(1) # one sample data

<TakeDataset element_spec=(TensorSpec(shape=(256,), dtype=tf.float64, name=None), TensorSpec(shape=(256,), dtype=tf.float64, name=None), TensorSpec(shape=(4,), dtype=tf.float64, name=None))>

In [22]:
def SentimentDatasetMapFunction(input_ids, attn_masks, labels):
    return {
        'input_ids': input_ids,
        'attention_mask': attn_masks
    }, labels

In [23]:
dataset = dataset.map(SentimentDatasetMapFunction) # converting to required format for tensorflow dataset

In [24]:
dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(256,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(256,), dtype=tf.float64, name=None)}, TensorSpec(shape=(4,), dtype=tf.float64, name=None))>

In [25]:
dataset = dataset.shuffle(10000).batch(16, drop_remainder=True) # batch size, drop any left out tensor

In [26]:
dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(16, 256), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(16, 256), dtype=tf.float64, name=None)}, TensorSpec(shape=(16, 4), dtype=tf.float64, name=None))>

In [27]:
p = 0.8
train_size = int((len(df)//16)*p) # for each 16 batch of data we will have len(df)//16 samples, take 80% of that for train.

In [28]:
train_size

4000

In [29]:
train_dataset = dataset.take(train_size)
val_dataset = dataset.skip(train_size)

In [30]:
from transformers import TFBertModel

In [31]:
model = TFBertModel.from_pretrained('bert-base-cased') # bert base model with pretrained weights

Downloading:   0%|          | 0.00/527M [00:00<?, ?B/s]

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [32]:
# defining 2 input layers for input_ids and attn_masks
input_ids = tf.keras.layers.Input(shape=(256,), name='input_ids', dtype='int32')
attn_masks = tf.keras.layers.Input(shape=(256,), name='attention_mask', dtype='int32')

bert_embds = model.bert(input_ids, attention_mask=attn_masks)[1] # 0 -> activation layer (3D), 1 -> pooled output layer (2D)
intermediate_layer = tf.keras.layers.Dense(512, activation='relu', name='intermediate_layer')(bert_embds)
output_layer = tf.keras.layers.Dense(4, activation='softmax', name='output_layer')(intermediate_layer) # softmax -> calcs probs of classes

bert_model = tf.keras.Model(inputs=[input_ids, attn_masks], outputs=output_layer)
bert_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 256)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 256)]        0           []                               
                                                                                                  
 bert (TFBertMainLayer)         TFBaseModelOutputWi  108310272   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 256,                                           

In [33]:
optim = tf.keras.optimizers.Adam(learning_rate=1e-5, decay=1e-6)
loss_func = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

In [34]:
bert_model.compile(optimizer=optim, loss=loss_func, metrics=[acc])

In [35]:
hist = bert_model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=3
)

Epoch 1/3
4000/4000 [==============================] - 3517s 877ms/step - loss: 1.3942 - accuracy: 0.2520 - val_loss: 1.3909 - val_accuracy: 0.2504
Epoch 2/3
4000/4000 [==============================] - 3508s 877ms/step - loss: 1.3922 - accuracy: 0.2503 - val_loss: 1.3931 - val_accuracy: 0.2480
Epoch 3/3
4000/4000 [==============================] - 3508s 877ms/step - loss: 1.3919 - accuracy: 0.2497 - val_loss: 1.3912 - val_accuracy: 0.2528


In [ ]:
import pickle
filename = 'ML4Crypto_birtmodelpkl'
pickle.dump(bert_model, open(filename, 'wb'))